version: '3.8'

services:
  kku-id-hub:
    container_name: kku-id-hub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: always